{% set name = "eth-keyfile" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8621c35e83cbc05909d2f23dbb8a87633918733caea553ae0e298f6a06291526

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - setuptools-markdown
  run:
    - eth-keys >=0.4.0
    - eth-utils >=2.0.0
    - py_ecc >=5.2.0
    - pycryptodome >=3.6.6,<4.0.0
    - python >={{ python_min }}

test:
  imports:
    - eth_keyfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/eth-keyfile
  summary: A library for handling the encrypted keyfiles used to store ethereum private keys.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
